### ISSUE TITLE
    NullInjectorError: No provider for AngularFireAuth!

### ISSUE THREAD

**Issue by sarancruzer** [codehandbook/AngularFirebaseLogin#1]
ERROR Error: Uncaught (in promise): Error: StaticInjectorError[AngularFireAuth]: 
  StaticInjectorError[AngularFireAuth]: 
    NullInjectorError: No provider for AngularFireAuth!
Error: StaticInjectorError[AngularFireAuth]: 
  StaticInjectorError[AngularFireAuth]: 
    NullInjectorError: No provider for AngularFireAuth!

**Comment by codehandbook** [comment]
@sarancruzer make sure you are using the following versions of firebase and angular fire for this source code to work.
```
npm install --save angularfire2@^5.0.0-rc.3
npm install --save firebase@4.6.1
```
